### PR TITLE
Feature/add gha

### PR DESCRIPTION
**Pull request by CAMOBAP**
GitHub actions

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@sshaw I will rebase it once #1 merged

**Comment by CAMOBAP** [comment]
@sshaw rebased, feel free to review

**Comment by sshaw** [comment]
Thanks again! I will do a release within the next day

**Comment by CAMOBAP** [comment]
@sshaw sorry I didn't actually execute tests on windows they failed because of the platform-specific path on windows in https://github.com/sshaw/ruby-jing/blob/master/test/test_jing.rb#L103.

Maybe make sense to wrap up it with `pathname` before comparison

**Comment by CAMOBAP** [comment]
Thanks a lot @sshaw  

Great idea to use GHA badges!
JFYI we also use RugyGems badge from ruby gems <a href="https://rubygems.org/gems/ruby-jing"></a>

**Pull request merged**
